# defaults for all clusters
defaults: {}

# defaults per sector
sectors:
  canary:
    deployment_strategy: "blue-green"
    monitoring_level: "verbose"
  prod-01:
    monitoring_level: "standard"
  prod-02:
    monitoring_level: "standard"

# defaults per region and mapping to sector
regions:
  us-east-1:
    sector: prod-02
    region: "us-east-1"
    timezone: "America/New_York"
  us-east-2:
    sector: prod-01
    region: "us-east-2"
    timezone: "America/New_York"
  us-west-2:
    sector: prod-01
    region: "us-west-2"
    timezone: "America/Los_Angeles"
  eu-west-1:
    sector: canary
    region: "eu-west-1"
    timezone: "Europe/London"

# clusters with their data
clusters:
- cluster_name: cluster-01
  region: eu-west-1
  data:
    cluster_key: c01
- cluster_name: cluster-02
  region: eu-west-1
  data:
    cluster_key: c02
- cluster_name: cluster-03
  region: us-east-1
  data:
    cluster_key: c03
