{{- $prefix := printf "%s-%s" .Values.region (index .Values "cluster_name") }}
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: {{ $prefix }}-pipelinerun-
  namespace: default
  labels:
    cluster: {{ index .Values "cluster_name" | quote }}
    region: {{ .Values.region | quote }}
    sector: {{ .Values.sector | quote }}
spec:
  pipelineRef:
    name: cluster-management
  params:
    - name: configmap
      value: {{ .Values.configmap | quote }}
    - name: pre-task-git-url
      value: {{ index .Values.tasks "pre-task-git-url" | quote }}
    - name: pre-task-path
      value: {{ index .Values.tasks "pre-task-path" | quote }}
    - name: pre-task-revision
      value: {{ index .Values.tasks "pre-task-revision" | quote }}
    - name: provision-task-git-url
      value: {{ index .Values.tasks "provision-task-git-url" | quote }}
    - name: provision-task-path
      value: {{ index .Values.tasks "provision-task-path" | quote }}
    - name: provision-task-revision
      value: {{ index .Values.tasks "provision-task-revision" | quote }}
    - name: post-task-git-url
      value: {{ index .Values.tasks "post-task-git-url" | quote }}
    - name: post-task-path
      value: {{ index .Values.tasks "post-task-path" | quote }}
    - name: post-task-revision
      value: {{ index .Values.tasks "post-task-revision" | quote }}
    {{- if hasKey $.Values "run-pre" }}
    - name: run-pre
      value: {{ index $.Values "run-pre" }}
    {{- end }}
    {{- if hasKey $.Values "run-provision" }}
    - name: run-provision
      value: {{ index $.Values "run-provision" }}
    {{- end }}
    {{- if hasKey $.Values "run-post" }}
    - name: run-post
      value: {{ index $.Values "run-post" }}
    {{- end }}
