apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: provision-eks-cluster
spec:
  params:
  - name: cluster-name
    type: string
    default: aws-cluster-01
  - name: target-role-arn
    type: string
    default: arn:aws:iam::123456789012:role/frm-poc-provisioning-role