apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: central-control-plane-pipelines
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jmelis/regionality
    targetRevision: HEAD
    path: central-control-plane/pipelines
  destination:
    server: https://kubernetes.default.svc
    namespace: clusters
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
