apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-configmaps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jmelis/regionality
    targetRevision: prerender-configmaps
    path: configs/configmaps
  destination:
    server: https://kubernetes.default.svc
    namespace: clusters
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
