apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cluster-management
  namespace: default
spec:
  params:
  # configmap
  - name: configmap
    type: string
    description: Name of the configmap containing cluster configuration

  # pre-task
  - name: pre-task-git-url
    type: string
    description: Git URL for pre-provision task
    default: "https://github.com/jmelis/regionality.git"
  - name: pre-task-path
    type: string
    description: Path to pre-provision task in git repo
    default: "providers/aws/tasks/pre-task.yaml"
  - name: pre-task-revision
    type: string
    description: Git revision for pre-provision task
    default: "HEAD"

  # provision-task
  - name: provision-task-git-url
    type: string
    description: Git URL for provision task
    default: "https://github.com/jmelis/regionality.git"
  - name: provision-task-path
    type: string
    description: Path to provision task in git repo
    default: "providers/aws/tasks/provision-task.yaml"
  - name: provision-task-revision
    type: string
    description: Git revision for provision task
    default: "HEAD"

  # post-task
  - name: post-task-git-url
    type: string
    description: Git URL for post-provision task
    default: "https://github.com/jmelis/regionality.git"
  - name: post-task-path
    type: string
    description: Path to post-provision task in git repo
    default: "providers/aws/tasks/post-task.yaml"
  - name: post-task-revision
    type: string
    description: Git revision for post-provision task
    default: "HEAD"

  # selectively run tasks
  - name: run-pre
    type: string
    default: "true"
    description: Whether to run the pre-provision task (true/false)
  - name: run-provision
    type: string
    default: "true"
    description: Whether to run the provision task (true/false)
  - name: run-post
    type: string
    default: "true"
    description: Whether to run the post-provision task (true/false)
  tasks:
  - name: pre-task
    when:
    - input: $(params.run-pre)
      operator: in
      values: ["true"]
    taskRef:
      resolver: git
      params:
      - name: url
        value: $(params.pre-task-git-url)
      - name: pathInRepo
        value: $(params.pre-task-path)
      - name: revision
        value: $(params.pre-task-revision)
    params:
    - name: configmap
      value: $(params.configmap)
  - name: provision-task
    when:
    - input: $(params.run-provision)
      operator: in
      values: ["true"]
    taskRef:
      resolver: git
      params:
      - name: url
        value: $(params.provision-task-git-url)
      - name: pathInRepo
        value: $(params.provision-task-path)
      - name: revision
        value: $(params.provision-task-revision)
    params:
    - name: configmap
      value: $(params.configmap)
    runAfter: [pre-task]
  - name: post-task
    when:
    - input: $(params.run-post)
      operator: in
      values: ["true"]
    taskRef:
      resolver: git
      params:
      - name: url
        value: $(params.post-task-git-url)
      - name: pathInRepo
        value: $(params.post-task-path)
      - name: revision
        value: $(params.post-task-revision)
    params:
    - name: configmap
      value: $(params.configmap)
    runAfter: [provision-task]
