---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.CLUSTER_NAME }}"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jmelis/regionality.git
    targetRevision: main
    path: providers/aws/provision/
    helm:
      values: |
        {{- .Values | toYaml | nindent 8 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
