---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.region }}-{{ .Values.clusterName }}"
  namespace: argocd
  labels:
    provision-pipeline: "true"
    cluster: "{{ .Values.clusterName }}"
    region: "{{ .Values.region }}"
    sector: "{{ .Values.sector }}"
spec:
  project: default
  source:
    repoURL: https://github.com/jmelis/regionality.git
    targetRevision: {{ .Values.targetRevision | quote }}
    path: providers/aws/provision/
    helm:
      valueFiles:
      - ../../../configs/values/{{ .Values.region }}-{{ .Values.clusterName }}-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
