{{- range .Values.clusters }}
{{- $regionConfig := index $.Values.regions .region }}
{{- $sectorDefaults := index $.Values.sectors $regionConfig.sector }}
{{- $mergedData := merge .data $regionConfig.data $sectorDefaults.data $.Values.defaults.data }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .cluster_name }}-configmap
  namespace: clusters
data:
{{- range $key, $value := $mergedData }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
