apiVersion: v1
data:
  ACM_VERSION: '2.14'
  CLUSTER_NAME: cluster-02
  KUBERNETES_VERSION: '1.29'
  PROVISION_APPLICATION_PATH: providers/aws/provision-application
  PROVISION_PATH: providers/aws/provision
  PROVISION_REPO: https://github.com/jmelis/regionality.git
  PROVISION_REVISION: prerender-configmaps
  REGION: us-east-2
  ROLE_ARN: arn:aws:iam::100000000002:role/central-control-plane
  SECTOR: prod-01
  WORKER_MACHINE_COUNT: '6'
  WORKER_MACHINE_TYPE: m5.xlarge
kind: ConfigMap
metadata:
  name: us-east-2-cluster-02-config
  namespace: default
