apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: provision-cluster
spec:
  params:
  - name: cluster-name
    type: string
  - name: cluster-config-path
    type: string
  - name: access-key-id
    type: string
  - name: secret-access-key
    type: string
  - name: session-token
    type: string
  steps:
  - name: provision
    image: bitnami/kubectl:1.28
    env:
    - name: AWS_ACCESS_KEY_ID
      value: $(params.access-key-id)
    - name: AWS_SECRET_ACCESS_KEY
      value: $(params.secret-access-key)
    - name: AWS_SESSION_TOKEN
      value: $(params.session-token)
    script: |
      #!/bin/bash
      set -e
      
      echo "Applying cluster configuration..."
      kubectl apply -k $(params.cluster-config-path)
      
      echo "Waiting for cluster $(params.cluster-name)..."
      kubectl wait --for=condition=Ready cluster/$(params.cluster-name) --timeout=1800s