apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: assume-role
spec:
  params:
  - name: target-role-arn
    type: string
  results:
  - name: access-key-id
  - name: secret-access-key
  - name: session-token
  steps:
  - name: assume-role
    image: amazon/aws-cli:2.13.0
    script: |
      #!/bin/bash
      set -e
      
      CREDS=$(aws sts assume-role \
        --role-arn $(params.target-role-arn) \
        --role-session-name tekton-provisioning \
        --output json)
      
      echo -n $(echo $CREDS | jq -r '.Credentials.AccessKeyId') > $(results.access-key-id.path)
      echo -n $(echo $CREDS | jq -r '.Credentials.SecretAccessKey') > $(results.secret-access-key.path)
      echo -n $(echo $CREDS | jq -r '.Credentials.SessionToken') > $(results.session-token.path)