{{- range $clusterName, $clusterConfig := .Values.clusters }}
{{- $regionConfig := index $.Values.regions $clusterConfig.region }}
{{- $sectorDefaults := index $.Values.sectors $regionConfig.sector }}
{{- $mergedData := merge $clusterConfig.data $regionConfig.data $sectorDefaults.data $.Values.defaults.data }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $clusterName }}-configmap
  namespace: default
data:
  CLUSTER_NAME: {{ $clusterName }}
{{- range $key, $value := $mergedData }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
