apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config-regional-access-cluster-ap-south
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jmelis/regionality
    targetRevision: HEAD
    path: overlays/clusters/regional-access-cluster-ap-south
  destination:
    server: https://kubernetes.default.svc
    namespace: clusters
  syncPolicy:
    automated:
      prune: true
      selfHeal: true