apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config-regional-cluster-eu-west
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jmelis/regionality
    targetRevision: HEAD
    path: overlays/clusters/regional-cluster-eu-west
  destination:
    server: https://kubernetes.default.svc
    namespace: clusters
  syncPolicy:
    automated:
      prune: true
      selfHeal: true