apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: provision-task
  namespace: default
spec:
  params:
  - name: configmap
    type: string
    description: Name of the configmap containing cluster configuration
  volumes:
  - name: config-volume
    configMap:
      name: $(params.configmap)
  steps:
  - name: provision
    image: alpine:latest
    envFrom:
    - configMapRef:
        name: $(params.configmap)
    script: |
      #!/bin/sh
      set -exvo pipefail

      echo "=== PROVISION TASK ==="
      env | sort

      apk add --no-cache git helm kubectl

      git clone $PROVISION_REPO repo
      (cd repo && git checkout $PROVISION_REVISION)

      TARGET_REVISION=$(cd repo && git rev-parse HEAD)

      helm template --set clusterName=$CLUSTER_NAME --set region=$REGION --set sector=$SECTOR --set targetRevision=$TARGET_REVISION repo/$PROVISION_APPLICATION_PATH | kubectl apply -f -

      # wait for application to be synced
      kubectl wait application -n argocd ${REGION}-${CLUSTER_NAME} --for=jsonpath='{.status.sync.status}'=Synced --timeout=300s
